openapi: 3.0.0
info:
  title: API de Teste
  description: API para teste v2
  version: 1.0.0
servers:
  - url: https://{region}.execute-api.amazonaws.com/{stage}
    variables:
      region:
        default: us-east-2
      stage:
        default: prod
paths:
  /teste:
    get:
      summary: Obter informações de teste
      operationId: getTeste
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Criar um novo teste
      operationId: postTeste
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Deletar um teste
      operationId: deleteTeste
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string