openapi: 3.0.0
info:
  title: Survival Prediction API
  version: 1.0.0
  description: API para prever a probabilidade de sobrevivência com base em características fornecidas.
servers:
  - url: https://api.example.com
    description: exemplo simples de url. 
paths:
  /sobreviventes:
    post:
      summary: Prever a probabilidade de sobrevivência
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caracteristicas:
                  type: array
                  items:
                    type: number
                  description: Array de 8 características
                  example: [70, 1, 1, 30.25, 0, 0, 1, 0] 
      responses:
        '200':
          description: Probabilidade de sobrevivência calculada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ID do usuário
                  survival_probability:
                    type: string
                    description: Probabilidade de sobrevivência em porcentagem
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Array de características não fornecido ou inválido
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Erro ao inserir no DynamoDB
    get:
      summary: Obter probabilidade de sobrevivência por ID de usuário ou listar IDs de usuários
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
          required: false
          description: ID do usuário
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ID do usuário
                  survival_probability:
                    type: string
                    description: Probabilidade de sobrevivência em porcentagem
                  user_ids:
                    type: array
                    items:
                      type: string
                    description: Lista de IDs de usuários
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuário não encontrado
    delete:
      summary: Deletar um usuário por ID
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
          required: true
          description: ID do usuário
      responses:
        '200':
          description: Usuário deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Usuário {user_id} deletado com sucesso
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: user_id é obrigatório
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Erro ao deletar usuário
components:
  schemas:
    Caracteristicas:
      type: array
      items:
        type: number
      description: Array de 8 características
      example: [70, 1, 1, 30.25, 0, 0, 1, 0]
    User:
      type: object
      properties:
        user_id:
          type: string
          description: ID do usuário
        survival_probability:
          type: string
          description: Probabilidade de sobrevivência em porcentagem